pipeline {
    agent {
        docker {
            image 'node:6-alpine' // Build Continaer for Node JS Image
            args '-p 3000:3000'   // Expose it to this local host server
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
    }
}
